import Brand from '@/applications/infocms/Brand'
import Article from '@/applications/infocms/Article'
import CultureArticle from '@/applications/infocms/CultureArticle'
import CultureCategory from '@/applications/infocms/CultureCategory'
import Human from '@/applications/infocms/Human'
import Knowledge from '@/applications/infocms/Knowledge'
import Website from '@/applications/infocms/Website'
import Pet from '@/applications/infocms/Pet'
import PetArticle from '@/applications/infocms/PetArticle'
import PetInfosort from '@/applications/infocms/PetInfosort'
import PetPetsort from '@/applications/infocms/PetPetsort'
import PetSort from '@/applications/infocms/PetSort'
import Product from '@/applications/infocms/Product'
import Store from '@/applications/infocms/Store'
import Subject from '@/applications/infocms/Subject'
import Goods from '@/applications/infocms/Goods'
import Category from '@/applications/infocms/Category'
import Type from '@/applications/infocms/Type'
import Attribute from '@/applications/infocms/Attribute'
import AttributeValue from '@/applications/infocms/AttributeValue'
import GoodsSku from '@/applications/infocms/GoodsSku'
import WebsiteGoods from '@/applications/infocms/WebsiteGoods'
import WebsiteSku from '@/applications/infocms/WebsiteSku'
import GoodsAttribute from '@/applications/infocms/GoodsAttribute'

export default {Brand, Article, CultureArticle, CultureCategory, Human, Knowledge, Website, Pet, PetArticle, PetInfosort, PetPetsort, PetSort, Product, Store, Subject, Goods, Category, Type, Attribute, AttributeValue, GoodsSku, WebsiteGoods, WebsiteSku, GoodsAttribute}
