import Brand from '@/applications/infocms/Brand'
import Article from '@/applications/infocms/Article'
import CultureArticle from '@/applications/infocms/CultureArticle'
import CultureCategory from '@/applications/infocms/CultureCategory'
import Human from '@/applications/infocms/Human'
import Knowledge from '@/applications/infocms/Knowledge'
import Mall from '@/applications/infocms/Mall'
import Pet from '@/applications/infocms/Pet'
import PetArticle from '@/applications/infocms/PetArticle'
import PetInfosort from '@/applications/infocms/PetInfosort'
import PetPetsort from '@/applications/infocms/PetPetsort'
import PetSort from '@/applications/infocms/PetSort'
import Product from '@/applications/infocms/Product'
import Store from '@/applications/infocms/Store'
import Subject from '@/applications/infocms/Subject'

export default {Brand, Article, CultureArticle, CultureCategory, Human, Knowledge, Mall, Pet, PetArticle, PetInfosort, PetPetsort, PetSort, Product, Store, Subject}
